trigger:
- main

pool:
  vmImage: 'vs2017-win2016' # This corresponds to Hosted VS2017

steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'HelloWorld.ps1' # Path to your existing PowerShell script in the repo
  displayName: 'Run HelloWorld Script'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)' # The folder where your artifacts are located
    ArtifactName: 'drop' # The name of the artifact, as specified
    publishLocation: 'Container' # Publishing to Azure DevOps (formerly Visual Studio Team Services)
  displayName: 'Publish Artifact: drop'

